# Generated by Django 4.0.4 on 2022-05-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('team_number', models.IntegerField()),
                ('person1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person3_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person4_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person5_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person6_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person7_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person8_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person9_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person10_name', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
